
#define CHINESE

#ifdef CHINESE

#define TXT_NUMBER_OF_BLOCKS    "  总方块数: "
#define TXT_ERR_BLOCKS          "\t错误: 方块数量必须大于0."
#define TXT_INFO_FOR_BLOCK      "\n=== 方块 #%d 信息 ===\n"
#define TXT_INIT_STATE          "  初始状态: "
#define TXT_ERR_ILLEGAL_STATE   "  \t错误: 非法的状态数值!\n"
#define TXT_REENTER             "  \t请重新输入...\n"
#define TXT_NUM_RELATIVE        "  关联方块数(自己也算): "
#define TXT_ERR_RELATIVE        "\t错误: 关联方块数不能多于方块总数!\n"
#define TXT_RELATIVE_NUMBER     "\t输入第 %d/%d 个关联方块编号: "
#define TXT_ERR_RELATIVE_LARGE  "\t\t错误: 关联方块编号不能多余方块总数!\n"
#define TXT_MUST_WITHIN         "\n 限定在多少步内完成: "
#define TXT_ERR_MAX_DEPTH       "\t错误: 最多不能超过 %d 步!\n"
#define TXT_ALREADY_SOLVED0     "\t这个问题此前已经解开了，无需再解\n"
#define TXT_ALREADY_SOLVED1     "\t看一下附近有无宝箱？\n"
#define TXT_FOUND_SOLUTIONS     "找到 %d 种解法。\n"
#define TXT_BEST_SOLUTION       "\n=== 最短解法 ===\n"
#define TXT_SHOW_OTHER_SOLUTION "要查看其它 %d 种解法吗? (Y/N): "
#define TXT_SOLUTION_NUM        "\n=== 解法 #%d ===\n"
#define TXT_UNABLE_SOLVE0       "\t未能在 %d 步内解开这道题，\n"
#define TXT_UNABLE_SOLVE1       "\t请检查输入的数据是否有误。\n"
#define TXT_SOLVED_IN           "共用 %d 步: \n"
#define TXT_HIT_BLOCK           "\t击打 %d 号方块\n"
#define TXT_SOLVING             "\n正在解题...\n"
#define TXT_GENSHIN_SOLVER      "|    Genshin Block Solver    |\n"
#define TXT_STATE_MIN           "  最小状态值(若不确定请填 1): "
#define TXT_STATE_MAX           "  最大状态值(自转型=4, 点亮型=3): "
#define TXT_STATE_TARGET        "  目标状态值(自转型=4, 点亮型=3或2): "
#define TXT_ERR_MAX_MIN         "  最大状态值不能小于最小状态值!"
#define TXT_ERR_TARGET          "\t错误: 目标状态必须在最小状态（含）和最大状态（含）之间。"
#define TXT_EXIT                "\n\t=== 程序结束，按任意键退出 ===\n"

#else

#define TXT_NUMBER_OF_BLOCKS    "  Number of blocks: "
#define TXT_ERR_BLOCKS          "\tError: Number of blocks must > 0."
#define TXT_INFO_FOR_BLOCK      "\n=== Info for Block #%d ===\n"
#define TXT_INIT_STATE          "  Init state: "
#define TXT_ERR_ILLEGAL_STATE   "  \tError: illegal state!\n"
#define TXT_REENTER             "  \tPlease re-enter...\n"
#define TXT_NUM_RELATIVE        "  Number of relative blocks (including self): "
#define TXT_ERR_RELATIVE        "\tError: relatives must no more than blocks!\n"
#define TXT_RELATIVE_NUMBER     "\t(%d/%d) Relative block number: "
#define TXT_ERR_RELATIVE_LARGE  "\t\tError: relative number too large!\n"
#define TXT_MUST_WITHIN         "\n Must Within how many steps: "
#define TXT_ERR_MAX_DEPTH       "\tError: max depth no more than %d!\n"
#define TXT_ALREADY_SOLVED0     "\tThe problem seems to be already solved.\n"
#define TXT_ALREADY_SOLVED1     "\tCheck if teasure chests are around you.\n"
#define TXT_FOUND_SOLUTIONS     "Found %d solution(s).\n"
#define TXT_BEST_SOLUTION       "\n=== Best Solution ===\n"
#define TXT_SHOW_OTHER_SOLUTION "Show other %d solution(s)? (Y/N): "
#define TXT_SOLUTION_NUM        "\n=== Solution #%d ===\n"
#define TXT_UNABLE_SOLVE0       "\tUnable to solve this problem\n"
#define TXT_UNABLE_SOLVE1       "\tin a maximum of %d steps.\n"
#define TXT_SOLVED_IN           "Solved in %d steps:\n"
#define TXT_HIT_BLOCK           "\tHit block #%d\n"
#define TXT_SOLVING             "\nSolving...\n"
#define TXT_GENSHIN_SOLVER      "|    Genshin Block Solver    |\n"
#define TXT_STATE_MIN           "  Minimum state(Fill in 1 if not sure): "
#define TXT_STATE_MAX           "  Maximum state(Self-rotate=4, Flower-like=3): "
#define TXT_STATE_TARGET        "  Target state(Self-rotate=4, Flower-like=3or2): "
#define TXT_ERR_MAX_MIN         "  Maximum state must not less than minimum state!"
#define TXT_ERR_TARGET          "\tError: Target state must within min (inclusive) and max (inclusive)."
#define TXT_EXIT                "\n\t=== Program finished. Press any key to exit. ===\n"

#endif

// g++ block2d.cpp main.cpp -O3 -o genshin_block_solver.exe
